# Generated by Django 3.1.7 on 2021-04-08 21:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.editor'),
            preserve_default=False,
        ),
    ]
