# Generated by Django 3.1.7 on 2021-04-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_editor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={'ordering': ['first_name']},
        ),
    ]
